language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- fab build
- ls -al
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIDIGJHF2U3NLRAEA
  secret_access_key:
    secure: "MDSbKkpAI4HUfQ5pP6jwFtI5dt89pIfdIs6tN+oMDIw/aes63JHzXHPhNFrGzZAebfD3RYEbW82PQkuWGrGjpkbdAckcfV8N0hoAMPE09XVmljBSwXlfwI+zFpwd/OLG9L3hYVwK0KA39Sg5ZxvQv01kKg7FbqW9KPTrEz5xq/s="
  bucket: tryton.openlabs.us
  endpoint: tryton.openlabs.us.s3-website-us-east-1.amazonaws.com
  region: us-east-1
  local-dir: output
  on:
    repo: openlabs/tryton.openlabs.us
